import Head from 'next/head'
import fs from 'fs'
import matter from 'gray-matter'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import md from 'markdown-it'


export default function PostPage({ frontmatter, content }) {
  return (
      <Head>
        <title>Exeter Tiny House Community</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>,
    <div className='mx-auto prose'>
      <h1 className="text-5xl mb-7">{frontmatter.title}</h1>
      <div dangerouslySetInnerHTML={{ __html: md().render(content) }} />
    </div>
  );
}

export async function getStaticProps() {
  const fileName = fs.readFileSync(`posts/home.md`, 'utf-8');
  const { data: frontmatter, content } = matter(fileName);
  return {
    props: {
      frontmatter,
      content,
    },
  };
}

